# This is a basic workflow to help you get started with Actions

name: RCM_CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        # - windows-latest
        # - macos-latest
        python-version:
        - '3.6'
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout RCM
        uses: actions/checkout@v3
        with:
          repository: RemoteConnectionManager/RCM
          path: RCM

      - name: Check repo
        run: |
         ls

      # Runs a single command using the runners shell
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r RCM/rcm/client/requirements.txt

      - name: Test python
        run: |
          python --version
          python -c "import paramiko"
          # python -c "exec('try: import paramiko \nexcept: print(\'missing paramiko\')')"

      - name: Build externals
        run: |
         touch RCM/rcm/client/external/turbovnc

      - name: Build
        run: |
         pyinstaller RCM/rcm/client/rcm_client_qt.spec

      - name: Upload exe
        uses: actions/upload-artifact@v3
        with:
          name: pyinstaller exe
          path: |
            dist
